services:
  server:
    build: .
    command: node bot.js
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      NODE_ENV: production
      TOKEN: placeholder
      PREFIX: placeholder
    ports:
      - 6000:6000
