services:
  bot:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist
    develop:
      watch:
        - action: sync
          path: ./dist
          target: /src/dist
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      NODE_ENV: development
      TOKEN: ${TOKEN}
      PREFIX: ${PREFIX}
    ports:
      - 6000:6000
    depends_on:
      - tsc
    command: nodemon --watch dist dist/src/bot.js

  tsc:
    build: .
    command: npm run watch
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./dist:/usr/src/app/dist
