services:
  bot:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      NODE_ENV: production
      TOKEN: ${TOKEN}
      PREFIX: ${PREFIX}
    ports:
      - 6000:6000
    depends_on:
      - tsc

  tsc:
    build: .
    command: npm run watch
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
